Correctly set exit code when erroring

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -17,5 +17,5 @@ jobs:
           files: |
             grammar.peg.go
       - if: steps.verify-unchanged-grammar.outputs.files_changed == 'true'
-        run: echo "::error file=grammar.peg.go::Make sure you regenerate grammar.peg when making any changes"
+        run: echo "::error file=grammar.peg.go::Make sure you regenerate grammar.peg when making any changes" && exit 1
       - uses: golangci/golangci-lint-action@v3
